<?php //defined('BASEURL') ? NULL : define('BASEURL', 'http://localhost/system/system');
//require("config/db.php");
//require("class/init.php");
require("dal/account.php");
require("dal/activity.php");
require("dal/chart.php");
require("dal/transaction.php");
require("dal/transaction_general_general.php");
require("dal/transaction_transaction_type.php");
require("dal/traceability.php");
require("dal/type.php");
require("dal/applications.php");
require("dal/users.php");
require("dal/logedin.php");
require("dal/loginvalidity.php");
require 'accounts_logic.php';
require 'activity_logic.php';
require 'general_logic.php';
require 'transaction_logic.php';
require 'chart_logic.php';
require 'Output.php';
require 'access_logic.php';
require 'authentication_logic.php';
require 'timed_processes/validity_Check.php';
require 'injection_logic.php';

